import { PromoHeroCardData } from "@/components/home-render/types";

export const promoHeroGridCards: PromoHeroCardData[] = [
  {
    id: "PHGK000",
    subtitle: "At-home Treatments",
    title: "Dr Dennis Gross Delivers",
    description: "High-tech skincare that gives clinical-grade results but without the injectables.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwaafd91a7/pd_homepages/24_WK53/ddg.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
  {
    id: "PHGK001",
    subtitle: "Scent spotlight",
    title: "We've Fallen For Glossier Fleur",
    description: "New to the You family, Fleur is an airy, luminous floral fragrance boasting notes of osmanthus, ylang ylang and apricot.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwe321e3ed/pd_homepages/24_WK53/Glossier-Fleur.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
  {
    id: "PHGK002",
    subtitle: "New in",
    title: "Laneige's Glaze Craze Tinted Lip Serums Are Here",
    description: "Inspired by doughnut flavours, these viral tinted lip treats ensure visibly plump lips and a high-shine finish.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw0ae780d8/pd_homepages/24_WK53/Laneiege.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
  {
    id: "PHGK003",
    subtitle: "Hair essentials",
    title: "OUAI Wanna Get A-OUAI Kit",
    description: "Meet your new travel buddies! Stay smooth and nourished all over with indulgent textures and holiday-ready scents.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwc54be94e/pd_homepages/24_WK53/OUAI.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
  {
    id: "PHGK004",
    subtitle: "We love",
    title: "Our Paros Tides Collection",
    description: "Inspired by the Greek island, our new edit is brimming with refreshing aquatic notes to rebalance your mind and body.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw53856804/pd_homepages/24_WK53/paro.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
  {
    id: "PHGK005",
    subtitle: "Suncare Fave",
    title: "Lancaster's Sensitive Skin Saviour",
    description: "Sensitive skin? We’ve got you literally covered for the warmer months with Lancaster’s new SPF 50 mineral sunscreen.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw54cce204/pd_homepages/24_WK53/lancaster.jpg",
    btnText: "SHOP NOW",
    btnType: "link",
    link: "/",
  },
];
