import { PromoHeroCardData } from "@/components/home-render/types";

export const promoHeroCardData: PromoHeroCardData[] = [
  {
    id: "PHK000",
    title: "The Everything Shower Edit",
    subtitle: "Worth £165 • Yours For £70",
    description: "This luxury edit of bath, body and haircare is your cue to turn your space into a spa and treat yourself to some top-to-toe T.L.C.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw2f59af91/pd_homepages/24_WK53/EVERYTHING-SHOWER-MB.jpg",
    btnText: "SHOP NOW",
    btnType: "solid",
    link: "/",
  },
  {
    id: "PHK001",
    title: "The Look Of Love With Charlotte Tilbury",
    subtitle: "New in",
    description: "Celebrating all things love, the Pillow Talk Effect collection features four new lipsticks and two irresistible blush palettes.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwf21877de/pd_homepages/24_WK53/CT-HERO-MB.jpg",
    btnText: "SHOP NOW",
    link: "/",
    btnType: "solid",
  },
  {
    id: "PHK002",
    title: "Brighter Days With Tatcha",
    subtitle: "WE LOVE",
    description: "Merging a 12-hour time-release form of vitamin C with luscious textures, Tatcha's new brightening heroes work to illuminate and firm.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwe2c7618c/pd_homepages/24_WK53/TATCHA-MB.jpg",
    btnText: "SHOP NOW",
    link: "/",
    btnType: "solid",
  },
  {
    id: "PHK003",
    title: "Scents Of Exclusivity",
    subtitle: "Fragrance Spotlight",
    description: "You won't find these fragrances anywhere else other than here - Discover your new favourite now.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw14814423/pd_homepages/24_WK52/fragrance-mb.jpg",
    btnText: "SHOP NOW",
    link: "/",
    btnType: "solid",
  },
  {
    id: "PHK004",
    title: "Phlur Rose Whip Eau de Parfum",
    subtitle: "New & Exclusive",
    description: "A carnal and contemporary take on rose: this osmanthus, blackcurrant, cashmere wood and rose blend evokes intense, electric desire.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dwfcb2835c/pd_homepages/24_WK53/Phlur-MB-hero.jpg",
    btnText: "SHOP NOW",
    link: "/",
    btnType: "solid",
  },
  {
    id: "PHK005",
    title: "Westman Atelier The Sculpting & Blush Powder Duos",
    subtitle: "New & Exclusive",
    description: "It's all about the cheeks! Choose from three sculpting and blush duos, and three blush duos, to define and colour to perfection.",
    image: "https://www.spacenk.com/on/demandware.static/-/Library-Sites-spacenk-global/default/dw2066ac52/pd_homepages/24_WK53/westman-MB.jpg",
    btnText: "SHOP NOW",
    link: "/",
    btnType: "solid",
  },
];
